package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbAccessrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbAccessrecord extends BaseTbAccessrecord<TbAccessrecord> {
	public static final TbAccessrecord dao = new TbAccessrecord().dao();
}
