package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbCompanyuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCompanyuser extends BaseTbCompanyuser<TbCompanyuser> {
	public static final TbCompanyuser dao = new TbCompanyuser().dao();
}
