package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbDevice extends BaseTbDevice<TbDevice> {
	public static final TbDevice dao = new TbDevice().dao();
}
