package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbFailreceive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbFailreceive extends BaseTbFailreceive<TbFailreceive> {
	public static final TbFailreceive dao = new TbFailreceive().dao();
}
