package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbGroup extends BaseTbGroup<TbGroup> {
	public static final TbGroup dao = new TbGroup().dao();
}
