package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbPersonnel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPersonnel extends BaseTbPersonnel<TbPersonnel> {
	public static final TbPersonnel dao = new TbPersonnel().dao();
}
