package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbAccessrecord;
import com.xiaosong.model.base.BaseTbPtinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPtinfo extends BaseTbPtinfo<TbPtinfo> {
	public static final TbPtinfo dao = new TbPtinfo().dao();
}
