package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbRecordbackups;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRecordbackups extends BaseTbRecordbackups<TbRecordbackups> {
	public static final TbRecordbackups dao = new TbRecordbackups().dao();
}
