package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbServerinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbServerinfo extends BaseTbServerinfo<TbServerinfo> {
	public static final TbServerinfo dao = new TbServerinfo().dao();
}
