package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbShareroom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShareroom extends BaseTbShareroom<TbShareroom> {
	public static final TbShareroom dao = new TbShareroom().dao();
}
