package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbVisitor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbVisitor extends BaseTbVisitor<TbVisitor> {
	public static final TbVisitor dao = new TbVisitor().dao();
}
