package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbDevice<M extends BaseTbDevice<M>> extends Model<M> implements IBean {

	public M setDeviceId(java.lang.String deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}
	
	public java.lang.String getDeviceId() {
		return getStr("deviceId");
	}

	public M setDeviceMode(java.lang.String deviceMode) {
		set("deviceMode", deviceMode);
		return (M)this;
	}
	
	public java.lang.String getDeviceMode() {
		return getStr("deviceMode");
	}

	public M setDeviceIp(java.lang.String deviceIp) {
		set("deviceIp", deviceIp);
		return (M)this;
	}
	
	public java.lang.String getDeviceIp() {
		return getStr("deviceIp");
	}

	public M setDevicePort(java.lang.Integer devicePort) {
		set("devicePort", devicePort);
		return (M)this;
	}
	
	public java.lang.Integer getDevicePort() {
		return getInt("devicePort");
	}

	public M setFqTurnover(java.lang.String fqTurnover) {
		set("FQ_turnover", fqTurnover);
		return (M)this;
	}
	
	public java.lang.String getFqTurnover() {
		return getStr("FQ_turnover");
	}

	public M setEOut(java.lang.String eOut) {
		set("E_out", eOut);
		return (M)this;
	}
	
	public java.lang.String getEOut() {
		return getStr("E_out");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setDeviceType(java.lang.String deviceType) {
		set("deviceType", deviceType);
		return (M)this;
	}
	
	public java.lang.String getDeviceType() {
		return getStr("deviceType");
	}

	public M setContralFloor(java.lang.String contralFloor) {
		set("contralFloor", contralFloor);
		return (M)this;
	}

	public java.lang.String getContralFloor() {
		return getStr("contralFloor");
	}

	public M setRelayController(java.lang.String relayController) {
		set("relayController", relayController);
		return (M)this;
	}

	public java.lang.String getRelayController() {
		return getStr("relayController");
	}

	public M setRelayIP(java.lang.String relayIP) {
		set("relayIP", relayIP);
		return (M)this;
	}

	public java.lang.String getRelayIP() {
		return getStr("relayIP");
	}

	public M setRelayPort(java.lang.String relayPort) {
		set("relayPort", relayPort);
		return (M)this;
	}

	public java.lang.String getRelayPort() {
		return getStr("relayPort");
	}

	public M setAdmin(java.lang.String admin) {
		set("admin", admin);
		return (M)this;
	}
	
	public java.lang.String getAdmin() {
		return getStr("admin");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
