package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbShareroom<M extends BaseTbShareroom<M>> extends Model<M> implements IBean {

	public M setRecordId(java.lang.String recordId) {
		set("recordId", recordId);
		return (M)this;
	}
	
	public java.lang.String getRecordId() {
		return getStr("recordId");
	}

	public M setRoomId(java.lang.Integer roomId) {
		set("roomId", roomId);
		return (M)this;
	}
	
	public java.lang.Integer getRoomId() {
		return getInt("roomId");
	}

	public M setApplyUserId(java.lang.Integer applyUserId) {
		set("applyUserId", applyUserId);
		return (M)this;
	}
	
	public java.lang.Integer getApplyUserId() {
		return getInt("applyUserId");
	}

	public M setSoleCode(java.lang.String soleCode) {
		set("soleCode", soleCode);
		return (M)this;
	}
	
	public java.lang.String getSoleCode() {
		return getStr("soleCode");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setApplyDate(java.lang.String applyDate) {
		set("applyDate", applyDate);
		return (M)this;
	}
	
	public java.lang.String getApplyDate() {
		return getStr("applyDate");
	}

	public M setApplyStartTime(java.lang.String applyStartTime) {
		set("applyStartTime", applyStartTime);
		return (M)this;
	}
	
	public java.lang.String getApplyStartTime() {
		return getStr("applyStartTime");
	}

	public M setApplyEndTime(java.lang.String applyEndTime) {
		set("applyEndTime", applyEndTime);
		return (M)this;
	}
	
	public java.lang.String getApplyEndTime() {
		return getStr("applyEndTime");
	}

	public M setRecordStatus(java.lang.Integer recordStatus) {
		set("recordStatus", recordStatus);
		return (M)this;
	}
	
	public java.lang.Integer getRecordStatus() {
		return getInt("recordStatus");
	}

	public M setRoomAddr(java.lang.String roomAddr) {
		set("roomAddr", roomAddr);
		return (M)this;
	}
	
	public java.lang.String getRoomAddr() {
		return getStr("roomAddr");
	}

	public M setRoomOpenTime(java.lang.String roomOpenTime) {
		set("roomOpenTime", roomOpenTime);
		return (M)this;
	}
	
	public java.lang.String getRoomOpenTime() {
		return getStr("roomOpenTime");
	}

	public M setRoomCloseTime(java.lang.String roomCloseTime) {
		set("roomCloseTime", roomCloseTime);
		return (M)this;
	}
	
	public java.lang.String getRoomCloseTime() {
		return getStr("roomCloseTime");
	}

	public M setRoomStatus(java.lang.String roomStatus) {
		set("roomStatus", roomStatus);
		return (M)this;
	}
	
	public java.lang.String getRoomStatus() {
		return getStr("roomStatus");
	}

	public M setRoomMode(java.lang.String roomMode) {
		set("roomMode", roomMode);
		return (M)this;
	}
	
	public java.lang.String getRoomMode() {
		return getStr("roomMode");
	}

	public M setIdNo(java.lang.String idNo) {
		set("idNo", idNo);
		return (M)this;
	}
	
	public java.lang.String getIdNo() {
		return getStr("idNo");
	}

	public M setIsSued(java.lang.String isSued) {
		set("isSued", isSued);
		return (M)this;
	}
	
	public java.lang.String getIsSued() {
		return getStr("isSued");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("delFlag", delFlag);
		return (M)this;
	}
	
	public java.lang.String getDelFlag() {
		return getStr("delFlag");
	}

	public M setIsFlag(java.lang.String isFlag) {
		set("isFlag", isFlag);
		return (M)this;
	}
	
	public java.lang.String getIsFlag() {
		return getStr("isFlag");
	}

}
