package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbLicense<M extends BaseTbLicense<M>> extends Model<M> implements IBean {

    public M setId(Integer id) {
        set("id", id);
        return (M)this;
    }

    public Integer getId() {
        return getInt("id");
    }

    public M setSWJCode(String swjCode) {
        set("swjCode", swjCode);
        return (M)this;
    }

    public String getSWJCode() {
        return getStr("swjCode");
    }

    public M setMac(String mac) {
        set("mac", mac);
        return (M)this;
    }

    public String getMac() {
        return getStr("mac");
    }

    public M setBeginDate(String beginDate) {
        set("beginDate", beginDate);
        return (M)this;
    }

    public String getBeginDate() {
        return getStr("beginDate");
    }

    public M setEndDate(String endDate) {
        set("endDate", endDate);
        return (M)this;
    }

    public String getEndDate() {
        return getStr("endDate");
    }
}
