package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbPersonnel<M extends BaseTbPersonnel<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setGroupName(String groupName) {
		set("groupName", groupName);
		return (M)this;
	}

	public String getGroupName() {
		return getStr("groupName");
	}

	public M setUserName(String userName) {
		set("userName", userName);
		return (M)this;
	}

	public String getUserName() {
		return getStr("userName");
	}

	public M setStudentNumber(Integer studentNumber) {
		set("studentNumber", studentNumber);
		return (M)this;
	}

	public Integer getStudentNumber() {
		return getInt("studentNumber");
	}

	public M setCreationDate(String creationDate) {
		set("creationDate", creationDate);
		return (M)this;
	}

	public String getCreationDate() {
		return getStr("creationDate");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setUpdateDate(String expt1) {
		set("updateDate", expt1);
		return (M)this;
	}

	public String getUpdateDate() {
		return getStr("updateDate");
	}

	public M setDormitory(String dormitory) {
		set("dormitory", dormitory);
		return (M)this;
	}

	public String getDormitory() {
		return getStr("dormitory");
	}

	public M setIsAccommodation(String isAccommodation) {
		set("isAccommodation", isAccommodation);
		return (M)this;
	}

	public String getIsAccommodation() {
		return getStr("isAccommodation");
	}

	public M setExpt1(String expt1) {
		set("expt1", expt1);
		return (M)this;
	}

	public String getExpt1() {
		return getStr("expt1");
	}

}
