package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbStatement<M extends BaseTbStatement<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setAnimalHeat(String animalHeat) {
		set("animalHeat", animalHeat);
		return (M)this;
	}

	public String getAnimalHeat() {
		return getStr("animalHeat");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setDate(String date) {
		set("date", date);
		return (M)this;
	}

	public String getDate() {
		return getStr("date");
	}

	public M setUserName(String userName) {
		set("userName", userName);
		return (M)this;
	}

	public String getUserName() {
		return getStr("userName");
	}

	public M setGroupName(String groupName) {
		set("groupName", groupName);
		return (M)this;
	}

	public String getGroupName() {
		return getStr("groupName");
	}

	public M setStudentNumber(Integer studentNumber) {
		set("studentNumber", studentNumber);
		return (M)this;
	}

	public Integer getStudentNumber() {
		return getInt("studentNumber");
	}

	public M setExpt2(String expt2) {
		set("expt2", expt2);
		return (M)this;
	}

	public String getExpt2() {
		return getStr("expt2");
	}

}
