package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbPtinfo<M extends BaseTbPtinfo<M>> extends Model<M> implements IBean {

	public M setDeviceName(java.lang.String deviceName) {
		set("deviceName", deviceName);
		return (M)this;
	}

	public java.lang.String getDeviceName() {
		return getStr("deviceName");
	}

	public M setDeviceIP(java.lang.String deviceIP) {
		set("deviceIP", deviceIP);
		return (M)this;
	}

	public java.lang.String getDeviceIP() {
		return getStr("deviceIP");
	}

    public M setOrgCode(java.lang.String orgCode) {
        set("orgCode", orgCode);
        return (M)this;
    }

    public java.lang.String getOrgCode() {
        return getStr("orgCode");
    }
	public M setPingStatus(java.lang.String pingStatus) {
		set("pingStatus", pingStatus);
		return (M)this;
	}

	public java.lang.String getPingStatus() {
		return getStr("pingStatus");
	}

	public M setPingavg(java.lang.Double pingavg) {
		set("pingavg", pingavg);
		return (M)this;
	}

	public java.lang.Double getPingavg() {
		return getDouble("pingavg");
	}

	public M setPingloss(java.lang.String pingloss) {
		set("pingloss", pingloss);
		return (M)this;
	}

	public java.lang.String getPingloss() {
		return getStr("pingloss");
	}

	public M setTelStatus(java.lang.String telStatus) {
		set("telStatus", telStatus);
		return (M)this;
	}

	public java.lang.String getTelStatus() {
		return getStr("telStatus");
	}

	public M setExpt1(java.lang.String expt1) {
		set("expt1", expt1);
		return (M)this;
	}

	public java.lang.String getExpt1() {
		return getStr("expt1");
	}

	public M setExpt2(java.lang.String expt2) {
		set("expt2", expt2);
		return (M)this;
	}

	public java.lang.String getExpt2() {
		return getStr("expt2");
	}

	public M setFreshTime(java.lang.String freshTime) {
		set("freshTime", freshTime);
		return (M)this;
	}

	public java.lang.String getFreshTime() {
		return getStr("freshTime");
	}

	public M setCpu(java.lang.String cpu) {
		set("cpu", cpu);
		return (M)this;
	}

	public java.lang.String getCpu() {
		return getStr("cpu");
	}

	public M setMemory(java.lang.String memory) {
		set("memory", memory);
		return (M)this;
	}

	public java.lang.String getMemory() {
		return getStr("memory");
	}

	public M setLongStatus(java.lang.String longStatus) {
		set("longStatus", longStatus);
		return (M)this;
	}

	public java.lang.String getLongStatus() {
		return getStr("longStatus");
	}
}
