package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbDevicerelated<M extends BaseTbDevicerelated<M>> extends Model<M> implements IBean {

	public M setRelatedId(java.lang.Integer relatedId) {
		set("relatedId", relatedId);
		return (M)this;
	}
	
	public java.lang.Integer getRelatedId() {
		return getInt("relatedId");
	}

	public M setPospIP(java.lang.String pospIP) {
		set("pospIP", pospIP);
		return (M)this;
	}
	
	public java.lang.String getPospIP() {
		return getStr("pospIP");
	}

	public M setFaceIP(java.lang.String faceIP) {
		set("faceIP", faceIP);
		return (M)this;
	}
	
	public java.lang.String getFaceIP() {
		return getStr("faceIP");
	}

	public M setQRCodeIP(java.lang.String QRCodeIP) {
		set("QRCodeIP", QRCodeIP);
		return (M)this;
	}
	
	public java.lang.String getQRCodeIP() {
		return getStr("QRCodeIP");
	}

	public M setRelayIP(java.lang.String relayIP) {
		set("relayIP", relayIP);
		return (M)this;
	}
	
	public java.lang.String getRelayIP() {
		return getStr("relayIP");
	}

	public M setRelayPort(java.lang.String relayPort) {
		set("relayPort", relayPort);
		return (M)this;
	}
	
	public java.lang.String getRelayPort() {
		return getStr("relayPort");
	}

	public M setRelayOUT(java.lang.String relayOUT) {
		set("relayOUT", relayOUT);
		return (M)this;
	}
	
	public java.lang.String getRelayOUT() {
		return getStr("relayOUT");
	}

	public M setContralFloor(java.lang.String contralFloor) {
		set("contralFloor", contralFloor);
		return (M)this;
	}
	
	public java.lang.String getContralFloor() {
		return getStr("contralFloor");
	}

	public M setChannelNO(java.lang.String channelNO) {
		set("channelNO", channelNO);
		return (M)this;
	}
	
	public java.lang.String getChannelNO() {
		return getStr("channelNO");
	}

	public M setTurnOver(java.lang.String turnOver) {
		set("turnOver", turnOver);
		return (M)this;
	}
	
	public java.lang.String getTurnOver() {
		return getStr("turnOver");
	}

	public M setExpt1(java.lang.String expt1) {
		set("expt1", expt1);
		return (M)this;
	}
	
	public java.lang.String getExpt1() {
		return getStr("expt1");
	}

	public M setExpt2(java.lang.String expt2) {
		set("expt2", expt2);
		return (M)this;
	}
	
	public java.lang.String getExpt2() {
		return getStr("expt2");
	}

}
