package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbServerinfo<M extends BaseTbServerinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setValue1(java.lang.String value) {
		set("value1", value);
		return (M)this;
	}

	public java.lang.String getValue1() {
		return getStr("value1");
	}

	public M setServerUrl(java.lang.String serverUrl) {
		set("serverUrl", serverUrl);
		return (M)this;
	}
	
	public java.lang.String getServerUrl() {
		return getStr("serverUrl");
	}

	public M setServerPort(java.lang.String serverPort) {
		set("serverPort", serverPort);
		return (M)this;
	}
	
	public java.lang.String getServerPort() {
		return getStr("serverPort");
	}

	public M setPrivateKey(java.lang.String privateKey) {
		set("privateKey", privateKey);
		return (M)this;
	}
	
	public java.lang.String getPrivateKey() {
		return getStr("privateKey");
	}

	public M setCodeKey(java.lang.String codeKey) {
		set("codeKey", codeKey);
		return (M)this;
	}
	
	public java.lang.String getCodeKey() {
		return getStr("codeKey");
	}

	public M setNetStatus(java.lang.String netStatus) {
		set("netStatus", netStatus);
		return (M)this;
	}
	
	public java.lang.String getNetStatus() {
		return getStr("netStatus");
	}

	public M setMac(java.lang.String mac) {
		set("mac", mac);
		return (M)this;
	}
	
	public java.lang.String getMac() {
		return getStr("mac");
	}


	public M setValue2(java.lang.String value2) {
		set("value2", value2);
		return (M)this;
	}

	public java.lang.String getValue2() {
		return getStr("value2");
	}

	public M setServerUrl2(java.lang.String serverUrl2) {
		set("serverUrl2", serverUrl2);
		return (M)this;
	}

	public java.lang.String getServerUrl2() {
		return getStr("serverUrl2");
	}

	public M setServerPort2(java.lang.String serverPort2) {
		set("serverPort2", serverPort2);
		return (M)this;
	}

	public java.lang.String getServerPort2() {
		return getStr("serverPort2");
	}


	public M setToKen(java.lang.String token) {
		set("token", token);
		return (M)this;
	}

	public java.lang.String getToKen() {
		return getStr("token");
	}

	public M setNetappValue(java.lang.String netappValue) {
		set("netappValue", netappValue);
		return (M)this;
	}

	public java.lang.String getNetappValue() {
		return getStr("netappValue");
	}

	public M setNetStatus2(java.lang.String netStatus2) {
		set("netStatus2", netStatus2);
		return (M)this;
	}

	public java.lang.String getNetStatus2() {
		return getStr("netStatus2");
	}

}
