package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCompanyuser<M extends BaseTbCompanyuser<M>> extends Model<M> implements IBean {

	public M setCompanyUserId(java.lang.Integer companyUserId) {
		set("companyUserId", companyUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyUserId() {
		return getInt("companyUserId");
	}

	public M setCompanyId(java.lang.Integer companyId) {
		set("companyId", companyId);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyId() {
		return getInt("companyId");
	}

	public M setSectionId(java.lang.Integer sectionId) {
		set("sectionId", sectionId);
		return (M)this;
	}
	
	public java.lang.Integer getSectionId() {
		return getInt("sectionId");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setReceiveDate(java.lang.String receiveDate) {
		set("receiveDate", receiveDate);
		return (M)this;
	}
	
	public java.util.Date getReceiveDate() {
		return get("receiveDate");
	}

	public M setReceiveTime(java.lang.String receiveTime) {
		set("receiveTime", receiveTime);
		return (M)this;
	}
	
	public java.util.Date getReceiveTime() {
		return get("receiveTime");
	}

	public M setRoleType(java.lang.String roleType) {
		set("roleType", roleType);
		return (M)this;
	}
	
	public java.lang.String getRoleType() {
		return getStr("roleType");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setIdType(java.lang.String idType) {
		set("idType", idType);
		return (M)this;
	}
	
	public java.lang.String getIdType() {
		return getStr("idType");
	}

	public M setIdNO(java.lang.String idNO) {
		set("idNO", idNO);
		return (M)this;
	}
	
	public java.lang.String getIdNO() {
		return getStr("idNO");
	}

	public M setCompanyFloor(java.lang.String companyFloor) {
		set("companyFloor", companyFloor);
		return (M)this;
	}
	
	public java.lang.String getCompanyFloor() {
		return getStr("companyFloor");
	}

	public M setCurrentStatus(java.lang.String currentStatus) {
		set("currentStatus", currentStatus);
		return (M)this;
	}
	
	public java.lang.String getCurrentStatus() {
		return getStr("currentStatus");
	}

	public M setIsSued(java.lang.String isSued) {
		set("isSued", isSued);
		return (M)this;
	}
	
	public java.lang.String getIsSued() {
		return getStr("isSued");
	}

	public M setIsDel(java.lang.String isDel) {
		set("isDel", isDel);
		return (M)this;
	}
	
	public java.lang.String getIsDel() {
		return getStr("isDel");
	}

	public M setIdFrontImgUrl(java.lang.String idFrontImgUrl) {
		set("idFrontImgUrl", idFrontImgUrl);
		return (M)this;
	}
	
	public java.lang.String getIdFrontImgUrl() {
		return getStr("idFrontImgUrl");
	}

	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}

	public java.lang.String getPhoto() {
		return getStr("photo");
	}

	public M setQrCode(java.lang.String qrCode) {
		set("qrCode", qrCode);
		return (M)this;
	}

	public java.lang.String getQrCode() {
		return getStr("qrCode");
	}

	public M setCardInfo(java.lang.Integer cardInfo) {
		set("cardInfo", cardInfo);
		return (M)this;
	}

	public java.lang.Integer getCardInfo() {
		return getInt("cardInfo");
	}

}
